name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ vars.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ai4devs-b657b
